### ISSUE TITLE
Cannot resolve symbol 'ActionResult'

### ISSUE THREAD

**Issue by FluffyDev1** [Legacy-Fabric/fabric-example-mod#12]
https://prnt.sc/151wzx0

Why there's no ActionResult?

**Comment by BoogieMonster1O1** [comment]
this is a thing in fabric api
are you sure you have it in your dev env?

**Comment by FluffyDev1** [comment]
I have these libraries
https://prnt.sc/151y06b

**Comment by FluffyDev1** [comment]
hello?

**Comment by halotroop2288** [comment]
> I have these libraries

From what I can see in this screenshot, you do not have Legacy Fabric API installed. You must add it to your build.gradle file.
