### ISSUE TITLE
Problem when building

### ISSUE THREAD

**Issue by DeltaTauGamma** [Legacy-Fabric/fabric-example-mod#29]
An error : "No matching variant of net.legacyfabric:legacy-looming:1.3-SNAPSHOT:20230703.155032-20 was found", comes up whenever I build the project.
The only changed files are mod.json, mixin.json and build.gradle

**Comment by DeltaTauGamma** [comment]
The git one did work though

**Comment by DeltaTauGamma** [comment]
It also runs but I can't interact with the game

**Comment by thecatcore** [comment]
use java 17 while working on your mod
