### ISSUE TITLE
1.8.9 example mod does not use chocoloom

### ISSUE THREAD

**Issue by BoogieMonster1O1** [Legacy-Fabric/fabric-example-mod#7]
not using chocoloom causes a 200% increase in build times + extra build.gradle bloat

**Comment by BluCobalt** [comment]
not using chocoloom causes the example mod to actually function correctly

**Comment by BoogieMonster1O1** [comment]
> not using chocoloom causes the example mod to actually function correctly

removing build.gradle bloat fixes it

**Comment by BoogieMonster1O1** [comment]
`intermediaryUrl` :concern:

**Comment by BluCobalt** [comment]
chocoloom is based off of an ancient version of loom

**Comment by BoogieMonster1O1** [comment]
> chocoloom is based off of an ancient version of loom

chocoloom cherry picks modern loom's commits

**Comment by BluCobalt** [comment]
"cherry pick" != based off of modern version

**Comment by BoogieMonster1O1** [comment]
loom 0.5 was based on 0.4
0.4 was based on 0.2.7
0.2.7 was based on 0.2

**Comment by BluCobalt** [comment]
what is your point 
loom 0.6 is based off of 0.5
chocoloom jekan't is based off of 0.2.6

**Comment by BoogieMonster1O1** [comment]
based off of newer version != more advanced and powerful

**Comment by BoogieMonster1O1** [comment]
plus, jekan't mirrors (most if not) all features of 0.4
and has a bunch of epic goodies

**Comment by BoogieMonster1O1** [comment]
actually the latest version isnt jekan't

**Comment by BoogieMonster1O1** [comment]
its e3d1762

**Comment by BluCobalt** [comment]
https://www.youtube.com/watch?v=2ZIpFytCSVc
