### ISSUE TITLE
VS code ide support.

### ISSUE THREAD

**Issue by ghost** [Legacy-Fabric/fabric-example-mod#8]
Is there vs code support?

**Comment by PhoenixVX** [comment]
yes.

**Comment by ghost** [comment]
the virtual machine doesnt appear when i run the configuration

**Comment by PhoenixVX** [comment]
Mind trying `./gradlew runClient` or `gradlew.bat runClient` in the terminal?

**Comment by ghost** [comment]
Aight it works but is there any way to fix the configuration that it generates; for debugging purposes

**Comment by PhoenixVX** [comment]
Have you ran `./gradlew vscode`?

**Comment by ghost** [comment]
yes

**Comment by PhoenixVX** [comment]
@hYdos Said to report the issue to the fabric-example-mod. :irritatered:, I guess runClient is all you can do otherwise.

**Comment by ghost** [comment]
thanks

**Comment by BluCobalt** [comment]
closing because it's been 3 months
